# =============================
# Set BrowserStack Credentials
# =============================
# Add your BrowserStack userName and accessKey here or set BROWSERSTACK_USERNAME and
# BROWSERSTACK_ACCESS_KEY as env variables
userName: ${BROWSERSTACK_USERNAME}
accessKey: ${BROWSERSTACK_ACCESS_KEY}

# =============================
# BrowserStack SDK Settings
# =============================
# Reduce verbose output from BrowserStack SDK
verbose: false
logLevel: error
# Extended timeouts for long-running tests (5 minutes)
idleTimeout: 300000
commandTimeout: 300000

# ======================
# BrowserStack Reporting
# ======================
# The following capabilities are used to set up reporting on BrowserStack:
# Set 'projectName' to the name of your project. Example, Marketing Website
projectName: ${BROWSERSTACK_PROJECT_NAME}
# Set `buildName` as the name of the job / testsuite being run
buildName: ${BROWSERSTACK_BUILD_NAME}
# `buildIdentifier` is a unique id to differentiate every execution that gets appended to
# buildName. Choose your buildIdentifier format from the available expressions:
# ${BUILD_NUMBER} (Default): Generates an incremental counter with every execution
# ${DATE_TIME}: Generates a Timestamp with every execution. Eg. 05-Nov-19:30
# Read more about buildIdentifiers here -> https://www.browserstack.com/docs/automate/selenium/organize-tests
buildIdentifier: '${BROWSERSTACK_BUILD_IDENTIFIER}' # Supports strings along with either/both ${expression}

# =======================================
# Platforms (Browsers / Devices to test)
# =======================================
# Platforms object contains all the browser / device combinations you want to test on.
# Entire list available here -> (https://www.browserstack.com/list-of-browsers-and-platforms/automate)
platforms:
  - os: OS X
    osVersion: Tahoe
    browserName: chrome
    browserVersion: '141'
  - os: OS X
    osVersion: Tahoe
    browserName: playwright-firefox
    browserVersion: '140'
  - os: OS X
    osVersion: Tahoe
    browserName: playwright-webkit
    browserVersion: '26'
  # - os: iOS
  #   osVersion: 17.5
  #   browserName: safari
  #   device: iPhone 15 Pro
  #   browserstack.deviceName: iPhone 15 Pro
  #   browserstack.deviceOrientation: portrait
  #   browserstack.realMobile: true  
  # - os: iOS
  #   osVersion: 17.5
  #   browserName: playwright-firefox
  #   device: iPhone 15 Pro
  #   browserstack.deviceName: iPhone 15 Pro
  #   browserstack.deviceOrientation: portrait
  #   browserstack.realMobile: true  
  # - os: iOS
  #   osVersion: 17.5
  #   browserName:  playwright-chromium
  #   device: iPhone 15 Pro
  #   browserstack.deviceName: iPhone 15 Pro
  #   browserstack.deviceOrientation: portrait
  #   browserstack.realMobile: true  

# =======================
# Parallels per Platform
# =======================
# The number of parallel threads to be used for each platform set.
# BrowserStack's SDK runner will select the best strategy based on the configured value
#
# Example 1 - If you have configured 3 platforms and set `parallelsPerPlatform` as 2, a total of 6 (2 * 3) parallel threads will be used on BrowserStack
#
# Example 2 - If you have configured 1 platform and set `parallelsPerPlatform` as 5, a total of 5 (1 * 5) parallel threads will be used on BrowserStack
parallelsPerPlatform: 2

# ==========================================
# BrowserStack Local
# (For localhost, staging/private websites)
# ==========================================
# Set browserStackLocal to true if your website under test is not accessible publicly over the internet
# Learn more about how BrowserStack Local works here -> https://www.browserstack.com/docs/automate/selenium/local-testing-introduction
# browserstackLocal: true
# browserstackLocalOptions:
#   forceLocal: true
#   localIdentifier: 'colab-test-1'
#   skipCheck: true
#   forceProxy: true    
#   includeHosts:
#     - test-specright.pantheonsite.io
#   disableSSLValidation: true

 # <boolean> (Default false)
# browserStackLocalOptions:
# Options to be passed to BrowserStack local in-case of advanced configurations
  # localIdentifier: # <string> (Default: null) Needed if you need to run multiple instances of local.
  # forceLocal: true  # <boolean> (Default: false) Set to true if you need to resolve all your traffic via BrowserStack Local tunnel.
  # Entire list of arguments available here -> https://www.browserstack.com/docs/automate/selenium/manage-incoming-connections

framework: playwright
source: node-js-playwright-sample-sdk:v1

# ===================
# Debugging features
# ===================
consoleLogs: errors
# playwrightVersion: 1.53.0
debug: false
# networkLogs: true
# networkLogsOptions: true
# video: true

automation: false

percy: true
percyCaptureMode: manual

accessibility: false

# Test Observability is an intelligent test reporting & debugging product. It collects data using the SDK. Read more about what data is collected at https://www.browserstack.com/docs/test-observability/references/terms-and-conditions
# Visit observability.browserstack.com to see your test reports and insights. To disable test observability, specify `testObservability: false` in the key below.
testObservability: false
